project:
  title: "Diplomatic Representation Data"
  type: website
  output-dir: docs
  
website:
  navbar:
    left: 
      - text: "Home"
        href: index.html
      - download.qmd

format:
  html:
    theme: morph
      
thme:      
  - custom.scss

